### ISSUE TITLE
LVMS EXTENDING SIZE: LAB08 -Q2

### ISSUE THREAD

**Issue by firasbenhmida** [halekammoun/RHCSA-Training#1]
lvextend -L +148M /dev/vg/lv0 ou lvextend -l 37 /dev/vg/lv0 
lvextend -l 37 /dev/vg/lv0 :Sets the size of the logical volume to 350 extents in total .
 But we need to add 350 extents    --->  lvextend -l +37 /dev/vg/lv0

**Comment by halekammoun** [comment]
Thank you for your observation! You’re correct in pointing out a misunderstanding here.
The command:
``` bash
lvextend -l 37 /dev/vg/lv0
```
sets the size of the logical volume to a total of 37 extents, rather than adding 37 extents. 
To increase the LV by 37 extents, the command should indeed be:
``` bash
lvextend -l +37 /dev/vg/lv0 ```
Thank you for helping clarify this distinction!
